### ISSUE TITLE
"Seiskan halkeama" first ascent?

### ISSUE THREAD

**Issue by jukuisma** [juusokorhonen/veikkola#6]
Hey,

I led a line today, which I believe is the project "Seiskan halkeama". The topo is quite vague so I'd like to get confirmation for this though before claiming the first ascent. The line is an offwidth climb to the right of a really hard looking finger crack, which is presumably "Kasin halkeama". It's quite a bit easier than a Finnish 7, but nothing else seems to make sense either. 

If this is "Seiskan halkeama", I can install `hugo` and create a pull request.

Picture of the line:

![image](https://user-images.githubusercontent.com/19922767/186757433-5ae0607f-56d4-4f7d-8966-bc32366ce100.png)

**Comment by juusokorhonen** [comment]
Hei Juho, välitän tämän kysymyksen Janille, koska en itsekään tiedä/muista enää reittien tarkkoja sijainteja, varsinkaan Eteläseinällä. 

Terveisin
 Juuso

—
Juuso Korhonen

**Comment by juusokorhonen** [comment]
JvP: "Kyseessä on Etelämuurin Kutosen halkeama jonka kiipesin 1977. Seiskan halkeama on tästä sdeuraava vasemmalla. Oikealla näkyy Erikoinen savutorvi joka on listattu väärin pääseinällä olevaksi (tai ainakin oli)."

Erikoinen savutorvi on siis väärin sijoitettuna pääseinälle: https://veikkola.greidi.net/topo/veikkola-trad/main-wall/erikoinen-savutorvi/ . Täytyy korjata tilanne.

Joten kiipeämäsi reitti on nähdäkseni "Ulkoneva halkeama (6-)": https://veikkola.greidi.net/topo/veikkola-trad/south-wall/ulkoneva-halkeama/ FA: JvP 1977

**Comment by jukuisma** [comment]
Kiitos tiedosta! Reitti tuntuikin juuri 6- tasolta ja Erikoisen savutorven siirtämisen jälkeen topot tekevät myös järkeä.
